  
name: mono repo deploy

deploy-design-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build design-system
        run: pnpm --filter @teddy/design-system build
      - name: Deploy design-system to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DESIGN_SYSTEM }}
          working-directory: packages/design-system

on:
  push:
    branches:
      - master

jobs:
  deploy-host:
    needs: deploy-design-system
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build host
        run: pnpm --filter host build
      - name: Deploy host to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_HOST }}
          working-directory: apps/host

  deploy-clients:
    needs: deploy-design-system
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build clients
        name: Vercel Multi Deploy

        on:
          push:
            branches:
              - master

        jobs:
          deploy-design-system:
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
              - name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '20.19.0'
              - name: Install pnpm
                run: npm install -g pnpm
              - name: Install dependencies
                run: pnpm install
              - name: Build design-system
                run: pnpm --filter @teddy/design-system build
              - name: Deploy design-system to Vercel
                uses: amondnet/vercel-action@v25
                with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DESIGN_SYSTEM }}
                  working-directory: packages/design-system

          deploy-host:
            needs: deploy-design-system
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
              - name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '20.19.0'
              - name: Install pnpm
                run: npm install -g pnpm
              - name: Install dependencies
                run: pnpm install
              - name: Build host
                run: pnpm --filter host build
              - name: Deploy host to Vercel
                uses: amondnet/vercel-action@v25
                with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_HOST }}
                  working-directory: apps/host

          deploy-clients:
            needs: deploy-design-system
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
              - name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '20.19.0'
              - name: Install pnpm
                run: npm install -g pnpm
              - name: Install dependencies
                run: pnpm install
              - name: Build clients
                run: pnpm --filter clients build
              - name: Deploy clients to Vercel
                uses: amondnet/vercel-action@v25
                with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_CLIENTS }}
                  working-directory: apps/clients
